package com.example.conversormonedas;
import javafx.collections.ObservableList;
import java.util.Arrays;
import java.util.List;

public class CurrencyCoins {

    public static void fillComboBox(ObservableList<Currency> comboBoxItems) {
        List<Currency> currencies = Arrays.asList(
                new Currency("USD", "Dólar estadounidense"),
                new Currency("AED", "Dirham de los Emiratos Árabes Unidos"),
                new Currency("AFN", "Afgani afgano"),
                new Currency("ALL", "Lek albanés"),
                new Currency("AMD", "Dram armenio"),
                new Currency("ANG", "Florín antillano neerlandés"),
                new Currency("AOA", "Kwanza angoleño"),
                new Currency("ARS", "Peso argentino"),
                new Currency("AUD", "Dólar australiano"),
                new Currency("AWG", "Florín arubeño"),
                new Currency("AZN", "Manat azerbaiyano"),
                new Currency("BAM", "Marco convertible de Bosnia y Herzegovina"),
                new Currency("BBD", "Dólar de Barbados"),
                new Currency("BDT", "Taka bangladesí"),
                new Currency("BGN", "Lev búlgaro"),
                new Currency("BHD", "Dinar bareiní"),
                new Currency("BIF", "Franco burundés"),
                new Currency("BMD", "Dólar de Bermudas"),
                new Currency("BND", "Dólar de Brunei"),
                new Currency("BOB", "Boliviano boliviano"),
                new Currency("BRL", "Real brasileño"),
                new Currency("BSD", "Dólar bahameño"),
                new Currency("BTN", "Ngultrum butanés"),
                new Currency("BWP", "Pula botsuano"),
                new Currency("BYN", "Rublo bielorruso"),
                new Currency("BZD", "Dólar beliceño"),
                new Currency("CAD", "Dólar canadiense"),
                new Currency("CDF", "Franco congoleño"),
                new Currency("CHF", "Franco suizo"),
                new Currency("CLP", "Peso chileno"),
                new Currency("CNY", "Yuan chino"),
                new Currency("COP", "Peso colombiano"),
                new Currency("CRC", "Colón costarricense"),
                new Currency("CUP", "Peso cubano"),
                new Currency("CVE", "Escudo caboverdiano"),
                new Currency("CZK", "Corona checa"),
                new Currency("DJF", "Franco yibutiano"),
                new Currency("DKK", "Corona danesa"),
                new Currency("DOP", "Peso dominicano"),
                new Currency("DZD", "Dinar argelino"),
                new Currency("EGP", "Libra egipcia"),
                new Currency("ERN", "Nakfa eritreo"),
                new Currency("ETB", "Birr etíope"),
                new Currency("EUR", "Euro"),
                new Currency("FJD", "Dólar fiyiano"),
                new Currency("FKP", "Libra malvinense"),
                new Currency("FOK", "Corona feroesa"),
                new Currency("GBP", "Libra esterlina"),
                new Currency("GEL", "Lari georgiano"),
                new Currency("GGP", "Libra de Guernsey"),
                new Currency("GHS", "Cedi ghanés"),
                new Currency("GIP", "Libra de Gibraltar"),
                new Currency("GMD", "Dalasi gambiano"),
                new Currency("GNF", "Franco guineano"),
                new Currency("GTQ", "Quetzal guatemalteco"),
                new Currency("GYD", "Dólar guyanés"),
                new Currency("HKD", "Dólar de Hong Kong"),
                new Currency("HNL", "Lempira hondureño"),
                new Currency("HRK", "Kuna croata"),
                new Currency("HTG", "Gourde haitiano"),
                new Currency("HUF", "Forint húngaro"),
                new Currency("IDR", "Rupia indonesia"),
                new Currency("ILS", "Nuevo shekel israelí"),
                new Currency("IMP", "Libra de Isla de Man"),
                new Currency("INR", "Rupia india"),
                new Currency("IQD", "Dinar iraquí"),
                new Currency("IRR", "Rial iraní"),
                new Currency("ISK", "Corona islandesa"),
                new Currency("JEP", "Libra de Jersey"),
                new Currency("JMD", "Dólar jamaicano"),
                new Currency("JOD", "Dinar jordano"),
                new Currency("JPY", "Yen japonés"),
                new Currency("KES", "Chelín keniata"),
                new Currency("KGS", "Som kirguís"),
                new Currency("KHR", "Riel camboyano"),
                new Currency("KID", "Dólar de Kiribati"),
                new Currency("KMF", "Franco comorense"),
                new Currency("KRW", "Won surcoreano"),
                new Currency("KWD", "Dinar kuwaití"),
                new Currency("KYD", "Dólar de Islas Caimán"),
                new Currency("KZT", "Tenge kazajo"),
                new Currency("LAK", "Kip laosiano"),
                new Currency("LBP", "Libra libanesa"),
                new Currency("LKR", "Rupia de Sri Lanka"),
                new Currency("LRD", "Dólar liberiano"),
                new Currency("LSL", "Loti lesothense"),
                new Currency("LYD", "Dinar libio"),
                new Currency("MAD", "Dírham marroquí"),
                new Currency("MDL", "Leu moldavo"),
                new Currency("MGA", "Ariary malgache"),
                new Currency("MKD", "Dinar macedonio"),
                new Currency("MMK", "Kyat birmano"),
                new Currency("MNT", "Tugrik mongol"),
                new Currency("MOP", "Pataca de Macao"),
                new Currency("MRU", "Uguiya mauritana"),
                new Currency("MUR", "Rupia mauriciana"),
                new Currency("MVR", "Rufiyaa maldiva"),
                new Currency("MWK", "Kwacha malauí"),
                new Currency("MXN", "Peso mexicano"),
                new Currency("MYR", "Ringgit malayo"),
                new Currency("MZN", "Metical mozambiqueño"),
                new Currency("NAD", "Dólar namibio"),
                new Currency("NGN", "Naira nigeriano"),
                new Currency("NIO", "Córdoba nicaragüense"),
                new Currency("NOK", "Corona noruega"),
                new Currency("NPR", "Rupia nepalesa"),
                new Currency("NZD", "Dólar neozelandés"),
                new Currency("OMR", "Rial omaní"),
                new Currency("PAB", "Balboa panameño"),
                new Currency("PEN", "Sol peruano"),
                new Currency("PGK", "Kina de Papúa Nueva Guinea"),
                new Currency("PHP", "Peso filipino"),
                new Currency("PKR", "Rupia pakistaní"),
                new Currency("PLN", "Zloty polaco"),
                new Currency("PYG", "Guaraní paraguayo"),
                new Currency("QAR", "Riyal qatarí"),
                new Currency("RON", "Leu rumano"),
                new Currency("RSD", "Dinar serbio"),
                new Currency("RUB", "Rublo ruso"),
                new Currency("RWF", "Franco ruandés"),
                new Currency("SAR", "Riyal saudí"),
                new Currency("SBD", "Dólar de Islas Salomón"),
                new Currency("SCR", "Rupia de Seychelles"),
                new Currency("SDG", "Libra sudanesa"),
                new Currency("SEK", "Corona sueca"),
                new Currency("SGD", "Dólar de Singapur"),
                new Currency("SHP", "Libra de Santa Elena"),
                new Currency("SLL", "Leone sierraleonés"),
                new Currency("SOS", "Chelín somalí"),
                new Currency("SRD", "Dólar surinamés"),
                new Currency("SSP", "Libra sursudanesa"),
                new Currency("STN", "Dobra de Santo Tomé y Príncipe"),
                new Currency("SYP", "Libra siria"),
                new Currency("SZL", "Lilangeni suazi"),
                new Currency("THB", "Baht tailandés"),
                new Currency("TJS", "Somoni tayiko"),
                new Currency("TMT", "Manat turcomano"),
                new Currency("TND", "Dinar tunecino"),
                new Currency("TOP", "Pa'anga tongano"),
                new Currency("TRY", "Lira turca"),
                new Currency("TTD", "Dólar de Trinidad y Tobago"),
                new Currency("TVD", "Dólar de Tuvalu"),
                new Currency("TWD", "Nuevo dólar taiwanés"),
                new Currency("TZS", "Chelín tanzano"),
                new Currency("UAH", "Grivna ucraniana"),
                new Currency("UGX", "Chelín ugandés"),
                new Currency("UYU", "Peso uruguayo"),
                new Currency("UZS", "Som uzbeko"),
                new Currency("VES", "Bolívar venezolano"),
                new Currency("VND", "Dong vietnamita"),
                new Currency("VUV", "Vatu vanuatuense"),
                new Currency("WST", "Tala samoano"),
                new Currency("XAF", "Franco CFA de África Central"),
                new Currency("XCD", "Dólar del Caribe Oriental"),
                new Currency("XDR", "Derechos especiales de giro"),
                new Currency("XOF", "Franco CFA de África Occidental"),
                new Currency("XPF", "Franco CFP"),
                new Currency("YER", "Rial yemení"),
                new Currency("ZAR", "Rand sudafricano"),
                new Currency("ZMW", "Kwacha zambiano"),
                new Currency("ZWL", "Dólar zimbabuense")

        );

        // Agregar las opciones de monedas al ComboBox
        comboBoxItems.addAll(currencies);
    }
}
